### ISSUE TITLE
add --privacy option during mlat-client install

### ISSUE THREAD

**Issue by werretal** [jprochazka/adsb-exchange#17]
Consider adding the --privacy option during the setup of the mlat-client. I know that the coverage in political “dangerous” regions is bad anyway, but it might prevent feeders from feeding if plotted on the coverage map.

**Comment by Romeo-Golf** [comment]
I agree this could be useful, perhaps to follow other feeder networks by offering the ability to randomise the location by say 10km?

**Comment by jprochazka** [comment]
This cannot be done client side due to the fact by doing so all MLAT data you send will be garbage and will make all MLAT calculations your receiver is involved incorrect. Every network working with MLAT data requires the exact location of your receiver. It then is up to them to then ensure your position is kept private on their site if it is so desired.
